
+# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Default

steps:

- task: VisualStudioTestPlatformInstaller@1
  inputs:
    packageFeedSelector: 'nugetOrg'
    versionSelector: 'latestPreRelease'
- task: InstallTestCompleteAdapter@1
  inputs:
    preferredExecutor: 'TC'
    accessKey: 'b8254f83-b556-4dc6-90a0-a2419911ab6a'
    logsLevel: '0'
- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: '**/*.pjs'
    searchFolder: '$(System.DefaultWorkingDirectory)'
