



trigger:
- master

pool:
  name: Default

steps:
# Starter pipeline
- task: VisualStudioTestPlatformInstaller@1
  inputs:
    packageFeedSelector: 'nugetOrg'
    versionSelector: 'latestPreRelease'
- task: InstallTestCompleteAdapter@1
  inputs:
    preferredExecutor: 'TC'
    accessKey: 'b8254f83-b556-4dc6-90a0-a2419911ab6a'
    searchMode: 'ProjectItems'
    logsLevel: '0'

- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: '**/*.pjs'
    searchFolder: '$(System.DefaultWorkingDirectory)'
    testFiltercriteria: '@calculator=true'


